[tool.poetry]
name = "iot-data-engine"
version = "0.1.0"
description = ""
authors = ["Ana150 <79976673+Ana150@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
